server:
  port: 9527
spring:
  application:
    name: cloud-gateway9527
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 开启动态路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service   #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://cloud-payment-service
#          filters:
#            - AddRequestParameter=X-Request-Id,1024
          predicates:
            - Path=/test/**   #断言,路径相匹配的进行路由
            - After=2021-12-01T21:47:47.278138300+08:00[Asia/Shanghai]
            - Before=2021-12-31T21:47:47.278138300+08:00[Asia/Shanghai]
#            - Between=2021-12-01T21:47:47.278138300+08:00[Asia/Shanghai],2021-12-31T21:47:47.278138300+08:00[Asia/Shanghai]
#            - Cookie=username,xxyy
#            - Header=X-Request-Id
#            - Host=
#            - Method=POST
#            - Query=

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/
